// Catálogo de productos de compra habitual, agrupado por sección.
// unit = unidad en que se suele contar en casa. hue = tinte del marco de foto.
export const STORES = ['Mercadona', 'Carrefour', 'Lidl', 'Aldi', 'Dia', 'Alcampo', 'Eroski'];

export const AISLES = ['Frutas y verduras', 'Carnicería', 'Pescadería', 'Lácteos y huevos', 'Despensa', 'Congelados', 'Panadería', 'Bebidas'];

// Cifras de ejemplo para ilustrar un comparador de cesta — NO son precios reales ni en vivo.
export const EXAMPLE_MARKET_PRICES = [
  { key: 'leche', label: 'Leche entera (1 L)', tags: ['leche'], prices: { Mercadona: 0.95, Carrefour: 1.05, Dia: 0.89, Alcampo: 0.99, Lidl: 0.85, Eroski: 1.02 , Aldi: 0.82 } },
  { key: 'huevos', label: 'Huevos (docena)', tags: ['huevo'], prices: { Mercadona: 2.15, Carrefour: 2.4, Dia: 2.05, Alcampo: 2.2, Lidl: 1.95, Eroski: 2.3 , Aldi: 1.89 } },
  { key: 'pollo', label: 'Pechuga de pollo (1 kg)', tags: ['pollo'], prices: { Mercadona: 6.5, Carrefour: 6.9, Dia: 6.2, Alcampo: 6.4, Lidl: 5.95, Eroski: 6.7 , Aldi: 5.85 } },
  { key: 'arroz', label: 'Arroz (1 kg)', tags: ['arroz'], prices: { Mercadona: 1.35, Carrefour: 1.5, Dia: 1.2, Alcampo: 1.3, Lidl: 1.1, Eroski: 1.45 , Aldi: 1.05 } },
  { key: 'pasta', label: 'Pasta (500 g)', tags: ['pasta','espaguetis'], prices: { Mercadona: 0.85, Carrefour: 0.95, Dia: 0.75, Alcampo: 0.8, Lidl: 0.65, Eroski: 0.92 , Aldi: 0.62 } },
  { key: 'tomate', label: 'Tomate (1 kg aprox.)', tags: ['tomate'], prices: { Mercadona: 1.69, Carrefour: 2.15, Dia: 1.65, Alcampo: 1.75, Lidl: 1.59, Eroski: 1.89 , Aldi: 1.55 } },
  { key: 'pan', label: 'Pan de barra', tags: ['pan'], prices: { Mercadona: 0.65, Carrefour: 0.75, Dia: 0.6, Alcampo: 0.65, Lidl: 0.55, Eroski: 0.7 , Aldi: 0.52 } },
  { key: 'queso', label: 'Queso rallado (200 g)', tags: ['queso'], prices: { Mercadona: 1.9, Carrefour: 2.1, Dia: 1.85, Alcampo: 1.95, Eroski: 2.05 , Aldi: 1.75 } },
  { key: 'aceite', label: 'Aceite de oliva (1 L)', tags: ['aceite'], prices: { Mercadona: 5.4, Carrefour: 5.9, Dia: 5.1, Alcampo: 5.3, Lidl: 4.95, Eroski: 5.7 , Aldi: 4.85 } },
  { key: 'atun', label: 'Atún en lata (pack 3)', tags: ['atun'], prices: { Mercadona: 2.6, Carrefour: 2.9, Dia: 2.45, Alcampo: 2.55, Eroski: 2.8 , Aldi: 2.35 } },
  { key: 'platano', label: 'Plátanos (1 kg)', tags: ['platano'], prices: { Mercadona: 1.29, Carrefour: 1.45, Dia: 1.25, Alcampo: 1.35, Lidl: 1.19, Eroski: 1.4 , Aldi: 1.15 } },
  { key: 'manzana', label: 'Manzanas (1 kg)', tags: ['manzana'], prices: { Mercadona: 1.79, Carrefour: 1.95, Dia: 1.7, Alcampo: 1.85, Lidl: 1.65 , Aldi: 1.6 } },
  { key: 'yogur', label: 'Yogur natural (pack 8)', tags: ['yogur'], prices: { Mercadona: 1.6, Carrefour: 1.75, Dia: 1.5, Alcampo: 1.65, Lidl: 1.4, Eroski: 1.7 , Aldi: 1.35 } },
  { key: 'patata', label: 'Patatas (2 kg)', tags: ['patata'], prices: { Mercadona: 1.99, Carrefour: 2.2, Dia: 1.89, Alcampo: 2.05, Lidl: 1.79 , Aldi: 1.7 } },
  { key: 'cebolla', label: 'Cebollas (1 kg)', tags: ['cebolla'], prices: { Mercadona: 1.15, Carrefour: 1.3, Dia: 1.1, Alcampo: 1.2, Eroski: 1.25 , Aldi: 1.05 } },
  { key: 'pimiento', label: 'Pimientos (1 kg)', tags: ['pimiento'], prices: { Mercadona: 2.49, Carrefour: 2.7, Dia: 2.35, Alcampo: 2.55, Lidl: 2.2 , Aldi: 2.1 } },
  { key: 'garbanzos', label: 'Garbanzos cocidos (bote)', tags: ['garbanzos'], prices: { Mercadona: 0.75, Carrefour: 0.85, Dia: 0.7, Alcampo: 0.78, Eroski: 0.82 , Aldi: 0.68 } },
  { key: 'lentejas', label: 'Lentejas (500 g)', tags: ['lentejas'], prices: { Mercadona: 1.1, Carrefour: 1.25, Dia: 1.0, Alcampo: 1.15, Lidl: 0.95 , Aldi: 0.9 } },
  { key: 'cafe', label: 'Café molido (250 g)', tags: ['cafe'], prices: { Mercadona: 2.3, Carrefour: 2.5, Dia: 2.15, Alcampo: 2.35, Lidl: 2.05, Eroski: 2.45 , Aldi: 1.95 } },
  { key: 'agua', label: 'Agua mineral (pack 6x1,5L)', tags: ['agua'], prices: { Mercadona: 2.1, Carrefour: 2.3, Dia: 1.95, Alcampo: 2.15, Lidl: 1.85, Eroski: 2.25 , Aldi: 1.75 } },
];

export const PRODUCTS = [
  // Bebidas
  { id:'b-agua', name:'Agua mineral', aisle:'Bebidas', unit:'garrafa 5L', hue:200, tags:['agua'] },
  { id:'b-cocacola', name:'Coca-Cola', aisle:'Bebidas', unit:'botella 2L', hue:15, tags:['cocacola','refresco','cola'] },
  { id:'b-fanta-naranja', name:'Fanta naranja', aisle:'Bebidas', unit:'botella 2L', hue:35, tags:['fanta','refresco','naranja'] },
  { id:'b-fanta-limon', name:'Fanta limón', aisle:'Bebidas', unit:'botella 2L', hue:90, tags:['fanta','refresco','limon'] },
  { id:'b-aquarius', name:'Aquarius', aisle:'Bebidas', unit:'botella 1.5L', hue:60, tags:['aquarius','isotonica'] },
  { id:'b-nestea', name:'Nestea', aisle:'Bebidas', unit:'botella 1.5L', hue:80, tags:['nestea','te'] },
  { id:'b-monster', name:'Monster Energy', aisle:'Bebidas', unit:'lata', hue:130, tags:['monster','energetica'] },
  { id:'b-redbull', name:'Red Bull', aisle:'Bebidas', unit:'lata', hue:210, tags:['redbull','energetica'] },
  { id:'b-cerveza', name:'Cerveza', aisle:'Bebidas', unit:'pack 6', hue:45, tags:['cerveza'] },
  { id:'b-cerveza-sin', name:'Cerveza sin alcohol', aisle:'Bebidas', unit:'pack 6', hue:45, tags:['cerveza','sin alcohol'] },
  { id:'b-vino-tinto', name:'Vino tinto', aisle:'Bebidas', unit:'botella', hue:0, tags:['vino','tinto'] },
  { id:'b-vino-blanco', name:'Vino blanco', aisle:'Bebidas', unit:'botella', hue:70, tags:['vino','blanco'] },
  { id:'b-cava', name:'Cava', aisle:'Bebidas', unit:'botella', hue:75, tags:['cava','espumoso'] },
  { id:'b-zumo-naranja', name:'Zumo de naranja', aisle:'Bebidas', unit:'brick 1L', hue:35, tags:['zumo','naranja'] },
  { id:'b-zumo-melocoton', name:'Zumo de melocotón', aisle:'Bebidas', unit:'brick 1L', hue:40, tags:['zumo','melocoton'] },
  { id:'b-zumo-piña', name:'Zumo de piña', aisle:'Bebidas', unit:'brick 1L', hue:80, tags:['zumo','pina'] },
  { id:'b-tonica', name:'Tónica', aisle:'Bebidas', unit:'botella', hue:60, tags:['tonica'] },
  { id:'b-cola-cao', name:'Cola Cao', aisle:'Bebidas', unit:'bote', hue:35, tags:['cacao','colacao'] },
  { id:'b-cafe-molido', name:'Café molido', aisle:'Bebidas', unit:'paquete', hue:35, tags:['cafe'] },
  { id:'b-te-verde', name:'Té verde', aisle:'Bebidas', unit:'caja', hue:130, tags:['te'] },
  // Frutas y verduras
  { id:'p-patata', name:'Patatas', aisle:'Frutas y verduras', unit:'kg', hue:80, tags:['patata'] },
  { id:'p-cebolla', name:'Cebollas', aisle:'Frutas y verduras', unit:'ud', hue:75, tags:['cebolla'] },
  { id:'p-ajo', name:'Cabeza de ajos', aisle:'Frutas y verduras', unit:'ud', hue:70, tags:['ajo'] },
  { id:'p-tomate', name:'Tomates', aisle:'Frutas y verduras', unit:'ud', hue:30, tags:['tomate'] },
  { id:'p-cherry', name:'Tomates cherry', aisle:'Frutas y verduras', unit:'bandeja', hue:28, tags:['tomate','cherry'] },
  { id:'p-pimiento', name:'Pimiento rojo', aisle:'Frutas y verduras', unit:'ud', hue:32, tags:['pimiento'] },
  { id:'p-pimiento-v', name:'Pimiento verde', aisle:'Frutas y verduras', unit:'ud', hue:140, tags:['pimiento'] },
  { id:'p-calabacin', name:'Calabacín', aisle:'Frutas y verduras', unit:'ud', hue:135, tags:['calabacin'] },
  { id:'p-berenjena', name:'Berenjena', aisle:'Frutas y verduras', unit:'ud', hue:300, tags:['berenjena'] },
  { id:'p-zanahoria', name:'Zanahorias', aisle:'Frutas y verduras', unit:'bolsa', hue:50, tags:['zanahoria'] },
  { id:'p-lechuga', name:'Lechuga romana', aisle:'Frutas y verduras', unit:'ud', hue:135, tags:['lechuga'] },
  { id:'p-espinacas', name:'Espinacas frescas', aisle:'Frutas y verduras', unit:'bolsa', hue:145, tags:['espinacas'] },
  { id:'p-champi', name:'Champiñones', aisle:'Frutas y verduras', unit:'bandeja', hue:60, tags:['champiñones','setas'] },
  { id:'p-brocoli', name:'Brócoli', aisle:'Frutas y verduras', unit:'ud', hue:150, tags:['brocoli','verduras'] },
  { id:'p-coliflor', name:'Coliflor', aisle:'Frutas y verduras', unit:'ud', hue:90, tags:['coliflor'] },
  { id:'p-calabaza', name:'Calabaza', aisle:'Frutas y verduras', unit:'ud', hue:55, tags:['calabaza'] },
  { id:'p-aguacate', name:'Aguacates', aisle:'Frutas y verduras', unit:'ud', hue:130, tags:['aguacate'] },
  { id:'p-limon', name:'Limones', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['limon'] },
  { id:'p-lima', name:'Limas', aisle:'Frutas y verduras', unit:'ud', hue:120, tags:['lima'] },
  { id:'p-puerro', name:'Puerros', aisle:'Frutas y verduras', unit:'ud', hue:140, tags:['puerro'] },
  { id:'p-pepino', name:'Pepino', aisle:'Frutas y verduras', unit:'ud', hue:140, tags:['pepino'] },
  { id:'p-cebolleta', name:'Cebolletas', aisle:'Frutas y verduras', unit:'manojo', hue:140, tags:['cebolleta'] },
  { id:'p-platano', name:'Plátanos', aisle:'Frutas y verduras', unit:'ud', hue:95, tags:['platano'] },
  { id:'p-manzana', name:'Manzanas', aisle:'Frutas y verduras', unit:'ud', hue:60, tags:['manzana'] },
  { id:'p-jengibre', name:'Jengibre fresco', aisle:'Frutas y verduras', unit:'ud', hue:70, tags:['jengibre'] },
  { id:'p-perejil', name:'Perejil', aisle:'Frutas y verduras', unit:'manojo', hue:145, tags:['perejil'] },
  { id:'p-cilantro', name:'Cilantro', aisle:'Frutas y verduras', unit:'manojo', hue:145, tags:['cilantro'] },
  { id:'p-albahaca', name:'Albahaca', aisle:'Frutas y verduras', unit:'maceta', hue:145, tags:['albahaca'] },

  // Carnicería
  { id:'p-pollo-pechuga', name:'Pechuga de pollo', aisle:'Carnicería', unit:'bandeja', hue:35, tags:['pollo'] },
  { id:'p-pollo-muslo', name:'Muslos de pollo', aisle:'Carnicería', unit:'bandeja', hue:32, tags:['pollo'] },
  { id:'p-picada', name:'Carne picada mixta', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['carne','picada'] },
  { id:'p-ternera', name:'Filetes de ternera', aisle:'Carnicería', unit:'bandeja', hue:22, tags:['ternera','carne'] },
  { id:'p-solomillo', name:'Solomillo de cerdo', aisle:'Carnicería', unit:'ud', hue:28, tags:['cerdo','solomillo'] },
  { id:'p-panceta', name:'Panceta o bacon', aisle:'Carnicería', unit:'paquete', hue:25, tags:['bacon','panceta'] },
  { id:'p-jamon', name:'Jamón serrano', aisle:'Carnicería', unit:'paquete', hue:28, tags:['jamon'] },
  { id:'p-chorizo', name:'Chorizo', aisle:'Carnicería', unit:'ud', hue:30, tags:['chorizo'] },

  // Pescadería
  { id:'p-salmon', name:'Lomos de salmón', aisle:'Pescadería', unit:'bandeja', hue:35, tags:['salmon','pescado'] },
  { id:'p-merluza', name:'Merluza', aisle:'Pescadería', unit:'bandeja', hue:220, tags:['merluza','pescado'] },
  { id:'p-bacalao', name:'Bacalao', aisle:'Pescadería', unit:'bandeja', hue:225, tags:['bacalao','pescado'] },
  { id:'p-atun-fresco', name:'Atún fresco', aisle:'Pescadería', unit:'bandeja', hue:20, tags:['atun','pescado'] },
  { id:'p-gambas', name:'Gambas peladas', aisle:'Pescadería', unit:'bandeja', hue:30, tags:['gambas'] },
  { id:'p-mejillones', name:'Mejillones', aisle:'Pescadería', unit:'malla', hue:250, tags:['mejillones'] },

  // Lácteos y huevos
  { id:'p-huevos', name:'Huevos', aisle:'Lácteos y huevos', unit:'docena', hue:90, tags:['huevo'] },
  { id:'p-leche', name:'Leche', aisle:'Lácteos y huevos', unit:'litro', hue:85, tags:['leche'] },
  { id:'p-nata', name:'Nata para cocinar', aisle:'Lácteos y huevos', unit:'brick', hue:85, tags:['nata'] },
  { id:'p-mantequilla', name:'Mantequilla', aisle:'Lácteos y huevos', unit:'ud', hue:88, tags:['mantequilla'] },
  { id:'p-queso-rallado', name:'Queso rallado', aisle:'Lácteos y huevos', unit:'bolsa', hue:88, tags:['queso'] },
  { id:'p-mozzarella', name:'Mozzarella', aisle:'Lácteos y huevos', unit:'ud', hue:90, tags:['mozzarella','queso'] },
  { id:'p-parmesano', name:'Parmesano', aisle:'Lácteos y huevos', unit:'cuña', hue:85, tags:['parmesano','queso'] },
  { id:'p-lonchas', name:'Queso en lonchas', aisle:'Lácteos y huevos', unit:'paquete', hue:90, tags:['queso'] },
  { id:'p-yogur', name:'Yogur natural', aisle:'Lácteos y huevos', unit:'pack', hue:85, tags:['yogur'] },
  { id:'p-quesocrema', name:'Queso crema', aisle:'Lácteos y huevos', unit:'tarrina', hue:88, tags:['queso'] },
  { id:'p-tofu', name:'Tofu firme', aisle:'Lácteos y huevos', unit:'paquete', hue:90, tags:['tofu'] },

  // Despensa
  { id:'p-pasta', name:'Pasta corta', aisle:'Despensa', unit:'paquete', hue:70, tags:['pasta'] },
  { id:'p-espaguetis', name:'Espaguetis', aisle:'Despensa', unit:'paquete', hue:70, tags:['pasta','espaguetis'] },
  { id:'p-arroz', name:'Arroz redondo', aisle:'Despensa', unit:'paquete', hue:80, tags:['arroz'] },
  { id:'p-basmati', name:'Arroz basmati', aisle:'Despensa', unit:'paquete', hue:80, tags:['arroz'] },
  { id:'p-quinoa', name:'Quinoa', aisle:'Despensa', unit:'paquete', hue:75, tags:['quinoa'] },
  { id:'p-fideos', name:'Fideos de arroz', aisle:'Despensa', unit:'paquete', hue:70, tags:['fideos'] },
  { id:'p-lentejas', name:'Lentejas', aisle:'Despensa', unit:'paquete', hue:45, tags:['lentejas'] },
  { id:'p-garbanzos', name:'Garbanzos cocidos', aisle:'Despensa', unit:'bote', hue:50, tags:['garbanzos'] },
  { id:'p-alubias', name:'Alubias cocidas', aisle:'Despensa', unit:'bote', hue:45, tags:['alubias','judias'] },
  { id:'p-tomate-tri', name:'Tomate triturado', aisle:'Despensa', unit:'brick', hue:28, tags:['tomate'] },
  { id:'p-tomate-frito', name:'Tomate frito', aisle:'Despensa', unit:'brick', hue:30, tags:['tomate'] },
  { id:'p-atun-lata', name:'Atún en lata', aisle:'Despensa', unit:'pack', hue:25, tags:['atun'] },
  { id:'p-maiz', name:'Maíz dulce', aisle:'Despensa', unit:'lata', hue:95, tags:['maiz'] },
  { id:'p-aceitunas', name:'Aceitunas', aisle:'Despensa', unit:'bote', hue:130, tags:['aceituna'] },
  { id:'p-aceite', name:'Aceite de oliva virgen extra', aisle:'Despensa', unit:'botella', hue:110, tags:['aceite'] },
  { id:'p-soja', name:'Salsa de soja', aisle:'Despensa', unit:'botella', hue:40, tags:['soja'] },
  { id:'p-coco', name:'Leche de coco', aisle:'Despensa', unit:'lata', hue:88, tags:['coco'] },
  { id:'p-curry', name:'Curry en polvo', aisle:'Despensa', unit:'bote', hue:60, tags:['curry'] },
  { id:'p-pimenton', name:'Pimentón dulce', aisle:'Despensa', unit:'bote', hue:32, tags:['pimenton'] },
  { id:'p-comino', name:'Comino molido', aisle:'Despensa', unit:'bote', hue:45, tags:['comino'] },
  { id:'p-oregano', name:'Orégano', aisle:'Despensa', unit:'bote', hue:140, tags:['oregano'] },
  { id:'p-harina', name:'Harina de trigo', aisle:'Despensa', unit:'paquete', hue:85, tags:['harina'] },
  { id:'p-panrallado', name:'Pan rallado', aisle:'Despensa', unit:'paquete', hue:75, tags:['pan rallado'] },
  { id:'p-pesto', name:'Pesto', aisle:'Despensa', unit:'tarro', hue:140, tags:['pesto'] },
  { id:'p-caldo', name:'Caldo de pollo o verduras', aisle:'Despensa', unit:'brick', hue:55, tags:['caldo'] },
  { id:'p-tortillas', name:'Tortillas de trigo', aisle:'Despensa', unit:'paquete', hue:75, tags:['tortilla'] },
  { id:'p-nachos', name:'Nachos de maíz', aisle:'Despensa', unit:'bolsa', hue:80, tags:['nachos'] },

  // Congelados
  { id:'p-guisantes', name:'Guisantes congelados', aisle:'Congelados', unit:'bolsa', hue:140, tags:['guisantes'] },
  { id:'p-verduras-cong', name:'Verduras para wok congeladas', aisle:'Congelados', unit:'bolsa', hue:140, tags:['verduras'] },
  { id:'p-croquetas', name:'Croquetas', aisle:'Congelados', unit:'bolsa', hue:60, tags:['croqueta'] },
  { id:'p-gyozas', name:'Gyozas / dumplings', aisle:'Congelados', unit:'bolsa', hue:70, tags:['dumplings','gyoza'] },
  { id:'p-gambas-cong', name:'Gambas congeladas', aisle:'Congelados', unit:'bolsa', hue:30, tags:['gambas'] },
  { id:'p-espinacas-cong', name:'Espinacas congeladas', aisle:'Congelados', unit:'bolsa', hue:145, tags:['espinacas'] },
  { id:'p-pizza-base', name:'Bases de pizza', aisle:'Congelados', unit:'paquete', hue:70, tags:['pizza','masa'] },
  { id:'p-patatas-cong', name:'Patatas prefritas', aisle:'Congelados', unit:'bolsa', hue:80, tags:['patata'] },

  // Panadería
  { id:'p-pan', name:'Pan rústico', aisle:'Panadería', unit:'ud', hue:65, tags:['pan'] },
  { id:'p-molde', name:'Pan de molde', aisle:'Panadería', unit:'paquete', hue:75, tags:['pan'] },
  { id:'p-hamburguesa-pan', name:'Panes de hamburguesa', aisle:'Panadería', unit:'paquete', hue:70, tags:['pan'] },
  { id:'p-masamadre', name:'Pan de masa madre', aisle:'Panadería', unit:'ud', hue:60, tags:['pan'] },
  { id:'x-naranjas', name:'Naranjas', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['naranjas'] },
  { id:'x-mandarinas', name:'Mandarinas', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['mandarinas'] },
  { id:'x-peras', name:'Peras', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['peras'] },
  { id:'x-uvas', name:'Uvas', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['uvas'] },
  { id:'x-fresas', name:'Fresas', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['fresas'] },
  { id:'x-arandanos', name:'Arándanos', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['arandanos'] },
  { id:'x-frambuesas', name:'Frambuesas', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['frambuesas'] },
  { id:'x-kiwi', name:'Kiwi', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['kiwi'] },
  { id:'x-pina', name:'Piña', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['pina'] },
  { id:'x-mango', name:'Mango', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['mango'] },
  { id:'x-melon', name:'Melón', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['melon'] },
  { id:'x-sandia', name:'Sandía', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['sandia'] },
  { id:'x-melocoton', name:'Melocotón', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['melocoton'] },
  { id:'x-nectarinas', name:'Nectarinas', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['nectarinas'] },
  { id:'x-ciruelas', name:'Ciruelas', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['ciruelas'] },
  { id:'x-cerezas', name:'Cerezas', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['cerezas'] },
  { id:'x-granada', name:'Granada', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['granada'] },
  { id:'x-pomelo', name:'Pomelo', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['pomelo'] },
  { id:'x-batata', name:'Batata', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['batata'] },
  { id:'x-boniato', name:'Boniato', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['boniato'] },
  { id:'x-apio', name:'Apio', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['apio'] },
  { id:'x-acelgas', name:'Acelgas', aisle:'Frutas y verduras', unit:'bolsa', hue:100, tags:['acelgas'] },
  { id:'x-rucula', name:'Rúcula', aisle:'Frutas y verduras', unit:'bolsa', hue:100, tags:['rucula'] },
  { id:'x-canonigos', name:'Canónigos', aisle:'Frutas y verduras', unit:'bolsa', hue:100, tags:['canonigos'] },
  { id:'x-endivias', name:'Endivias', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['endivias'] },
  { id:'x-repollo', name:'Repollo', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['repollo'] },
  { id:'x-col-lombarda', name:'Col lombarda', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['col','lombarda'] },
  { id:'x-pak-choi', name:'Pak choi', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['pak','choi'] },
  { id:'x-judias-verdes', name:'Judías verdes', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['judias','verdes'] },
  { id:'x-esparragos-verdes', name:'Espárragos verdes', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['esparragos','verdes'] },
  { id:'x-alcachofas', name:'Alcachofas', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['alcachofas'] },
  { id:'x-remolacha', name:'Remolacha', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['remolacha'] },
  { id:'x-rabanos', name:'Rábanos', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['rabanos'] },
  { id:'x-nabo', name:'Nabo', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['nabo'] },
  { id:'x-hinojo', name:'Hinojo', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['hinojo'] },
  { id:'x-cebolla-morada', name:'Cebolla morada', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['cebolla','morada'] },
  { id:'x-cebolla-dulce', name:'Cebolla dulce', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['cebolla','dulce'] },
  { id:'x-tomate-pera', name:'Tomate pera', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['tomate','pera'] },
  { id:'x-tomate-raf', name:'Tomate raf', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['tomate','raf'] },
  { id:'x-tomate-kumato', name:'Tomate kumato', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['tomate','kumato'] },
  { id:'x-pimiento-amarillo', name:'Pimiento amarillo', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['pimiento','amarillo'] },
  { id:'x-pimiento-padron', name:'Pimiento padrón', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['pimiento','padron'] },
  { id:'x-setas-variadas', name:'Setas variadas', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['setas','variadas'] },
  { id:'x-shiitake', name:'Shiitake', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['shiitake'] },
  { id:'x-portobello', name:'Portobello', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['portobello'] },
  { id:'x-maiz-en-mazorca', name:'Maíz en mazorca', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['maiz','en','mazorca'] },
  { id:'x-ajo-tierno', name:'Ajo tierno', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['ajo','tierno'] },
  { id:'x-brotes-de-soja', name:'Brotes de soja', aisle:'Frutas y verduras', unit:'ud', hue:100, tags:['brotes','de','soja'] },
  { id:'x-hierbabuena', name:'Hierbabuena', aisle:'Frutas y verduras', unit:'bolsa', hue:100, tags:['hierbabuena'] },
  { id:'x-menta-fresca', name:'Menta fresca', aisle:'Frutas y verduras', unit:'bolsa', hue:100, tags:['menta','fresca'] },
  { id:'x-eneldo', name:'Eneldo', aisle:'Frutas y verduras', unit:'bolsa', hue:100, tags:['eneldo'] },
  { id:'x-romero-fresco', name:'Romero fresco', aisle:'Frutas y verduras', unit:'bolsa', hue:100, tags:['romero','fresco'] },
  { id:'x-tomillo-fresco', name:'Tomillo fresco', aisle:'Frutas y verduras', unit:'bolsa', hue:100, tags:['tomillo','fresco'] },
  { id:'x-contramuslos-de-pollo', name:'Contramuslos de pollo', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['contramuslos','de','pollo'] },
  { id:'x-alitas-de-pollo', name:'Alitas de pollo', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['alitas','de','pollo'] },
  { id:'x-pollo-entero', name:'Pollo entero', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['pollo','entero'] },
  { id:'x-pavo-fileteado', name:'Pavo fileteado', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['pavo','fileteado'] },
  { id:'x-carne-picada-de-ternera', name:'Carne picada de ternera', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['carne','picada','de','ternera'] },
  { id:'x-carne-picada-de-pollo', name:'Carne picada de pollo', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['carne','picada','de','pollo'] },
  { id:'x-hamburguesas-de-ternera', name:'Hamburguesas de ternera', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['hamburguesas','de','ternera'] },
  { id:'x-hamburguesas-de-pollo', name:'Hamburguesas de pollo', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['hamburguesas','de','pollo'] },
  { id:'x-entrecot-de-ternera', name:'Entrecot de ternera', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['entrecot','de','ternera'] },
  { id:'x-lomo-de-cerdo', name:'Lomo de cerdo', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['lomo','de','cerdo'] },
  { id:'x-costillas-de-cerdo', name:'Costillas de cerdo', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['costillas','de','cerdo'] },
  { id:'x-chuletas-de-cerdo', name:'Chuletas de cerdo', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['chuletas','de','cerdo'] },
  { id:'x-secreto-iberico', name:'Secreto ibérico', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['secreto','iberico'] },
  { id:'x-carrilleras-de-cerdo', name:'Carrilleras de cerdo', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['carrilleras','de','cerdo'] },
  { id:'x-conejo-troceado', name:'Conejo troceado', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['conejo','troceado'] },
  { id:'x-cordero-troceado', name:'Cordero troceado', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['cordero','troceado'] },
  { id:'x-pechuga-de-pavo', name:'Pechuga de pavo', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['pechuga','de','pavo'] },
  { id:'x-salchichas-frescas', name:'Salchichas frescas', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['salchichas','frescas'] },
  { id:'x-longaniza', name:'Longaniza', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['longaniza'] },
  { id:'x-jamon-cocido', name:'Jamón cocido', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['jamon','cocido'] },
  { id:'x-pavo-en-lonchas', name:'Pavo en lonchas', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['pavo','en','lonchas'] },
  { id:'x-mortadela', name:'Mortadela', aisle:'Carnicería', unit:'bandeja', hue:25, tags:['mortadela'] },
  { id:'x-dorada', name:'Dorada', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['dorada'] },
  { id:'x-lubina', name:'Lubina', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['lubina'] },
  { id:'x-sardinas', name:'Sardinas', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['sardinas'] },
  { id:'x-boquerones', name:'Boquerones', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['boquerones'] },
  { id:'x-caballa', name:'Caballa', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['caballa'] },
  { id:'x-trucha', name:'Trucha', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['trucha'] },
  { id:'x-lenguado', name:'Lenguado', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['lenguado'] },
  { id:'x-rodaballo', name:'Rodaballo', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['rodaballo'] },
  { id:'x-sepia', name:'Sepia', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['sepia'] },
  { id:'x-calamares', name:'Calamares', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['calamares'] },
  { id:'x-pulpo-cocido', name:'Pulpo cocido', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['pulpo','cocido'] },
  { id:'x-vieiras', name:'Vieiras', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['vieiras'] },
  { id:'x-almejas', name:'Almejas', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['almejas'] },
  { id:'x-berberechos', name:'Berberechos', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['berberechos'] },
  { id:'x-langostinos', name:'Langostinos', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['langostinos'] },
  { id:'x-gambon', name:'Gambón', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['gambon'] },
  { id:'x-anillas-de-calamar', name:'Anillas de calamar', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['anillas','de','calamar'] },
  { id:'x-palitos-de-cangrejo', name:'Palitos de cangrejo', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['palitos','de','cangrejo'] },
  { id:'x-salmon-ahumado', name:'Salmón ahumado', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['salmon','ahumado'] },
  { id:'x-atun-en-tacos', name:'Atún en tacos', aisle:'Pescadería', unit:'bandeja', hue:210, tags:['atun','en','tacos'] },
  { id:'x-leche-semidesnatada', name:'Leche semidesnatada', aisle:'Lácteos y huevos', unit:'L', hue:60, tags:['leche','semidesnatada'] },
  { id:'x-leche-desnatada', name:'Leche desnatada', aisle:'Lácteos y huevos', unit:'L', hue:60, tags:['leche','desnatada'] },
  { id:'x-bebida-de-avena', name:'Bebida de avena', aisle:'Lácteos y huevos', unit:'L', hue:60, tags:['bebida','de','avena'] },
  { id:'x-bebida-de-almendra', name:'Bebida de almendra', aisle:'Lácteos y huevos', unit:'L', hue:60, tags:['bebida','de','almendra'] },
  { id:'x-bebida-de-soja', name:'Bebida de soja', aisle:'Lácteos y huevos', unit:'L', hue:60, tags:['bebida','de','soja'] },
  { id:'x-kefir', name:'Kéfir', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['kefir'] },
  { id:'x-yogur-griego', name:'Yogur griego', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['yogur','griego'] },
  { id:'x-yogur-vegetal', name:'Yogur vegetal', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['yogur','vegetal'] },
  { id:'x-requeson', name:'Requesón', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['requeson'] },
  { id:'x-ricotta', name:'Ricotta', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['ricotta'] },
  { id:'x-queso-feta', name:'Queso feta', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['queso','feta'] },
  { id:'x-queso-de-cabra', name:'Queso de cabra', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['queso','de','cabra'] },
  { id:'x-queso-manchego', name:'Queso manchego', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['queso','manchego'] },
  { id:'x-queso-cheddar', name:'Queso cheddar', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['queso','cheddar'] },
  { id:'x-queso-emmental', name:'Queso emmental', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['queso','emmental'] },
  { id:'x-queso-azul', name:'Queso azul', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['queso','azul'] },
  { id:'x-burrata', name:'Burrata', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['burrata'] },
  { id:'x-mascarpone', name:'Mascarpone', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['mascarpone'] },
  { id:'x-nata-para-montar', name:'Nata para montar', aisle:'Lácteos y huevos', unit:'L', hue:60, tags:['nata','para','montar'] },
  { id:'x-creme-fraiche', name:'Crème fraîche', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['creme','fraiche'] },
  { id:'x-huevos-camperos', name:'Huevos camperos', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['huevos','camperos'] },
  { id:'x-claras-de-huevo', name:'Claras de huevo', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['claras','de','huevo'] },
  { id:'x-margarina', name:'Margarina', aisle:'Lácteos y huevos', unit:'ud', hue:60, tags:['margarina'] },
  { id:'x-cuscus', name:'Cuscús', aisle:'Despensa', unit:'paquete', hue:45, tags:['cuscus'] },
  { id:'x-bulgur', name:'Bulgur', aisle:'Despensa', unit:'paquete', hue:45, tags:['bulgur'] },
  { id:'x-arroz-integral', name:'Arroz integral', aisle:'Despensa', unit:'paquete', hue:45, tags:['arroz','integral'] },
  { id:'x-arroz-jazmin', name:'Arroz jazmín', aisle:'Despensa', unit:'paquete', hue:45, tags:['arroz','jazmin'] },
  { id:'x-arroz-arborio', name:'Arroz arborio', aisle:'Despensa', unit:'paquete', hue:45, tags:['arroz','arborio'] },
  { id:'x-arroz-salvaje', name:'Arroz salvaje', aisle:'Despensa', unit:'paquete', hue:45, tags:['arroz','salvaje'] },
  { id:'x-fideos-ramen', name:'Fideos ramen', aisle:'Despensa', unit:'paquete', hue:45, tags:['fideos','ramen'] },
  { id:'x-noodles-de-trigo', name:'Noodles de trigo', aisle:'Despensa', unit:'paquete', hue:45, tags:['noodles','de','trigo'] },
  { id:'x-semola', name:'Sémola', aisle:'Despensa', unit:'paquete', hue:45, tags:['semola'] },
  { id:'x-polenta', name:'Polenta', aisle:'Despensa', unit:'paquete', hue:45, tags:['polenta'] },
  { id:'x-avena-en-copos', name:'Avena en copos', aisle:'Despensa', unit:'paquete', hue:45, tags:['avena','en','copos'] },
  { id:'x-granola', name:'Granola', aisle:'Despensa', unit:'paquete', hue:45, tags:['granola'] },
  { id:'x-cereales-de-desayuno', name:'Cereales de desayuno', aisle:'Despensa', unit:'paquete', hue:45, tags:['cereales','de','desayuno'] },
  { id:'x-lentejas-cocidas', name:'Lentejas cocidas', aisle:'Despensa', unit:'paquete', hue:45, tags:['lentejas','cocidas'] },
  { id:'x-alubias-negras', name:'Alubias negras', aisle:'Despensa', unit:'paquete', hue:45, tags:['alubias','negras'] },
  { id:'x-alubias-rojas', name:'Alubias rojas', aisle:'Despensa', unit:'paquete', hue:45, tags:['alubias','rojas'] },
  { id:'x-judias-pintas', name:'Judías pintas', aisle:'Despensa', unit:'paquete', hue:45, tags:['judias','pintas'] },
  { id:'x-garbanzos-secos', name:'Garbanzos secos', aisle:'Despensa', unit:'paquete', hue:45, tags:['garbanzos','secos'] },
  { id:'x-soja-texturizada', name:'Soja texturizada', aisle:'Despensa', unit:'paquete', hue:45, tags:['soja','texturizada'] },
  { id:'x-tempeh', name:'Tempeh', aisle:'Despensa', unit:'paquete', hue:45, tags:['tempeh'] },
  { id:'x-tahini', name:'Tahini', aisle:'Despensa', unit:'paquete', hue:45, tags:['tahini'] },
  { id:'x-crema-de-cacahuete', name:'Crema de cacahuete', aisle:'Despensa', unit:'paquete', hue:45, tags:['crema','de','cacahuete'] },
  { id:'x-miel', name:'Miel', aisle:'Despensa', unit:'botella', hue:45, tags:['miel'] },
  { id:'x-sirope-de-arce', name:'Sirope de arce', aisle:'Despensa', unit:'botella', hue:45, tags:['sirope','de','arce'] },
  { id:'x-azucar-blanco', name:'Azúcar blanco', aisle:'Despensa', unit:'paquete', hue:45, tags:['azucar','blanco'] },
  { id:'x-azucar-moreno', name:'Azúcar moreno', aisle:'Despensa', unit:'paquete', hue:45, tags:['azucar','moreno'] },
  { id:'x-cacao-en-polvo', name:'Cacao en polvo', aisle:'Despensa', unit:'paquete', hue:45, tags:['cacao','en','polvo'] },
  { id:'x-chocolate-negro', name:'Chocolate negro', aisle:'Despensa', unit:'paquete', hue:45, tags:['chocolate','negro'] },
  { id:'x-chocolate-con-leche', name:'Chocolate con leche', aisle:'Despensa', unit:'paquete', hue:45, tags:['chocolate','con','leche'] },
  { id:'x-levadura-quimica', name:'Levadura química', aisle:'Despensa', unit:'paquete', hue:45, tags:['levadura','quimica'] },
  { id:'x-levadura-de-panadero', name:'Levadura de panadero', aisle:'Despensa', unit:'paquete', hue:45, tags:['levadura','de','panadero'] },
  { id:'x-maicena', name:'Maicena', aisle:'Despensa', unit:'paquete', hue:45, tags:['maicena'] },
  { id:'x-harina-integral', name:'Harina integral', aisle:'Despensa', unit:'paquete', hue:45, tags:['harina','integral'] },
  { id:'x-harina-de-maiz', name:'Harina de maíz', aisle:'Despensa', unit:'paquete', hue:45, tags:['harina','de','maiz'] },
  { id:'x-harina-de-garbanzo', name:'Harina de garbanzo', aisle:'Despensa', unit:'paquete', hue:45, tags:['harina','de','garbanzo'] },
  { id:'x-pan-rallado-panko', name:'Pan rallado panko', aisle:'Despensa', unit:'paquete', hue:45, tags:['pan','rallado','panko'] },
  { id:'x-vinagre-de-vino', name:'Vinagre de vino', aisle:'Despensa', unit:'botella', hue:45, tags:['vinagre','de','vino'] },
  { id:'x-vinagre-de-manzana', name:'Vinagre de manzana', aisle:'Despensa', unit:'botella', hue:45, tags:['vinagre','de','manzana'] },
  { id:'x-vinagre-de-arroz', name:'Vinagre de arroz', aisle:'Despensa', unit:'botella', hue:45, tags:['vinagre','de','arroz'] },
  { id:'x-vinagre-balsamico', name:'Vinagre balsámico', aisle:'Despensa', unit:'botella', hue:45, tags:['vinagre','balsamico'] },
  { id:'x-aceite-de-girasol', name:'Aceite de girasol', aisle:'Despensa', unit:'botella', hue:45, tags:['aceite','de','girasol'] },
  { id:'x-aceite-de-sesamo', name:'Aceite de sésamo', aisle:'Despensa', unit:'botella', hue:45, tags:['aceite','de','sesamo'] },
  { id:'x-salsa-teriyaki', name:'Salsa teriyaki', aisle:'Despensa', unit:'botella', hue:45, tags:['salsa','teriyaki'] },
  { id:'x-salsa-de-ostras', name:'Salsa de ostras', aisle:'Despensa', unit:'botella', hue:45, tags:['salsa','de','ostras'] },
  { id:'x-salsa-de-pescado', name:'Salsa de pescado', aisle:'Despensa', unit:'botella', hue:45, tags:['salsa','de','pescado'] },
  { id:'x-salsa-worcestershire', name:'Salsa Worcestershire', aisle:'Despensa', unit:'botella', hue:45, tags:['salsa','worcestershire'] },
  { id:'x-salsa-picante', name:'Salsa picante', aisle:'Despensa', unit:'botella', hue:45, tags:['salsa','picante'] },
  { id:'x-mostaza-dijon', name:'Mostaza Dijon', aisle:'Despensa', unit:'botella', hue:45, tags:['mostaza','dijon'] },
  { id:'x-mostaza-antigua', name:'Mostaza antigua', aisle:'Despensa', unit:'botella', hue:45, tags:['mostaza','antigua'] },
  { id:'x-mayonesa', name:'Mayonesa', aisle:'Despensa', unit:'botella', hue:45, tags:['mayonesa'] },
  { id:'x-ketchup', name:'Ketchup', aisle:'Despensa', unit:'botella', hue:45, tags:['ketchup'] },
  { id:'x-salsa-barbacoa', name:'Salsa barbacoa', aisle:'Despensa', unit:'botella', hue:45, tags:['salsa','barbacoa'] },
  { id:'x-salsa-de-tomate', name:'Salsa de tomate', aisle:'Despensa', unit:'botella', hue:45, tags:['salsa','de','tomate'] },
  { id:'x-pasta-de-tomate', name:'Pasta de tomate', aisle:'Despensa', unit:'paquete', hue:45, tags:['pasta','de','tomate'] },
  { id:'x-pasta-de-curry-rojo', name:'Pasta de curry rojo', aisle:'Despensa', unit:'paquete', hue:45, tags:['pasta','de','curry','rojo'] },
  { id:'x-pasta-de-curry-verde', name:'Pasta de curry verde', aisle:'Despensa', unit:'paquete', hue:45, tags:['pasta','de','curry','verde'] },
  { id:'x-pasta-de-miso', name:'Pasta de miso', aisle:'Despensa', unit:'paquete', hue:45, tags:['pasta','de','miso'] },
  { id:'x-caldo-de-pescado', name:'Caldo de pescado', aisle:'Despensa', unit:'paquete', hue:45, tags:['caldo','de','pescado'] },
  { id:'x-caldo-de-carne', name:'Caldo de carne', aisle:'Despensa', unit:'paquete', hue:45, tags:['caldo','de','carne'] },
  { id:'x-caldo-de-verduras', name:'Caldo de verduras', aisle:'Despensa', unit:'paquete', hue:45, tags:['caldo','de','verduras'] },
  { id:'x-coco-rallado', name:'Coco rallado', aisle:'Despensa', unit:'paquete', hue:45, tags:['coco','rallado'] },
  { id:'x-cacahuetes', name:'Cacahuetes', aisle:'Despensa', unit:'paquete', hue:45, tags:['cacahuetes'] },
  { id:'x-almendras', name:'Almendras', aisle:'Despensa', unit:'paquete', hue:45, tags:['almendras'] },
  { id:'x-nueces', name:'Nueces', aisle:'Despensa', unit:'paquete', hue:45, tags:['nueces'] },
  { id:'x-avellanas', name:'Avellanas', aisle:'Despensa', unit:'paquete', hue:45, tags:['avellanas'] },
  { id:'x-pistachos', name:'Pistachos', aisle:'Despensa', unit:'paquete', hue:45, tags:['pistachos'] },
  { id:'x-anacardos', name:'Anacardos', aisle:'Despensa', unit:'paquete', hue:45, tags:['anacardos'] },
  { id:'x-pinones', name:'Piñones', aisle:'Despensa', unit:'paquete', hue:45, tags:['pinones'] },
  { id:'x-pasas', name:'Pasas', aisle:'Despensa', unit:'paquete', hue:45, tags:['pasas'] },
  { id:'x-datiles', name:'Dátiles', aisle:'Despensa', unit:'paquete', hue:45, tags:['datiles'] },
  { id:'x-orejas-de-albaricoque-seco', name:'Orejas de albaricoque seco', aisle:'Despensa', unit:'paquete', hue:45, tags:['orejas','de','albaricoque','seco'] },
  { id:'x-semillas-de-chia', name:'Semillas de chía', aisle:'Despensa', unit:'paquete', hue:45, tags:['semillas','de','chia'] },
  { id:'x-semillas-de-lino', name:'Semillas de lino', aisle:'Despensa', unit:'paquete', hue:45, tags:['semillas','de','lino'] },
  { id:'x-semillas-de-sesamo', name:'Semillas de sésamo', aisle:'Despensa', unit:'paquete', hue:45, tags:['semillas','de','sesamo'] },
  { id:'x-pipas-de-girasol', name:'Pipas de girasol', aisle:'Despensa', unit:'paquete', hue:45, tags:['pipas','de','girasol'] },
  { id:'x-alcaparras', name:'Alcaparras', aisle:'Despensa', unit:'paquete', hue:45, tags:['alcaparras'] },
  { id:'x-pepinillos', name:'Pepinillos', aisle:'Despensa', unit:'paquete', hue:45, tags:['pepinillos'] },
  { id:'x-jalapenos-en-conserva', name:'Jalapeños en conserva', aisle:'Despensa', unit:'paquete', hue:45, tags:['jalapenos','en','conserva'] },
  { id:'x-tomates-secos', name:'Tomates secos', aisle:'Despensa', unit:'paquete', hue:45, tags:['tomates','secos'] },
  { id:'x-pimientos-del-piquillo', name:'Pimientos del piquillo', aisle:'Despensa', unit:'paquete', hue:45, tags:['pimientos','del','piquillo'] },
  { id:'x-esparragos-en-conserva', name:'Espárragos en conserva', aisle:'Despensa', unit:'paquete', hue:45, tags:['esparragos','en','conserva'] },
  { id:'x-champinones-en-conserva', name:'Champiñones en conserva', aisle:'Despensa', unit:'paquete', hue:45, tags:['champinones','en','conserva'] },
  { id:'x-palmitos', name:'Palmitos', aisle:'Despensa', unit:'paquete', hue:45, tags:['palmitos'] },
  { id:'x-alga-nori', name:'Alga nori', aisle:'Despensa', unit:'paquete', hue:45, tags:['alga','nori'] },
  { id:'x-wasabi', name:'Wasabi', aisle:'Despensa', unit:'paquete', hue:45, tags:['wasabi'] },
  { id:'x-tortillas-de-maiz', name:'Tortillas de maíz', aisle:'Despensa', unit:'paquete', hue:45, tags:['tortillas','de','maiz'] },
  { id:'x-pan-pita', name:'Pan pita', aisle:'Despensa', unit:'paquete', hue:45, tags:['pan','pita'] },
  { id:'x-wraps-integrales', name:'Wraps integrales', aisle:'Despensa', unit:'paquete', hue:45, tags:['wraps','integrales'] },
  { id:'x-galletas-saladas', name:'Galletas saladas', aisle:'Despensa', unit:'paquete', hue:45, tags:['galletas','saladas'] },
  { id:'x-tostadas-crujientes', name:'Tostadas crujientes', aisle:'Despensa', unit:'paquete', hue:45, tags:['tostadas','crujientes'] },
  { id:'x-brocoli-congelado', name:'Brócoli congelado', aisle:'Congelados', unit:'bolsa', hue:200, tags:['brocoli','congelado'] },
  { id:'x-coliflor-congelada', name:'Coliflor congelada', aisle:'Congelados', unit:'bolsa', hue:200, tags:['coliflor','congelada'] },
  { id:'x-judias-verdes-congeladas', name:'Judías verdes congeladas', aisle:'Congelados', unit:'bolsa', hue:200, tags:['judias','verdes','congeladas'] },
  { id:'x-frutos-rojos-congelados', name:'Frutos rojos congelados', aisle:'Congelados', unit:'bolsa', hue:200, tags:['frutos','rojos','congelados'] },
  { id:'x-mango-congelado', name:'Mango congelado', aisle:'Congelados', unit:'bolsa', hue:200, tags:['mango','congelado'] },
  { id:'x-salmon-congelado', name:'Salmón congelado', aisle:'Congelados', unit:'bolsa', hue:200, tags:['salmon','congelado'] },
  { id:'x-merluza-congelada', name:'Merluza congelada', aisle:'Congelados', unit:'bolsa', hue:200, tags:['merluza','congelada'] },
  { id:'x-bacalao-congelado', name:'Bacalao congelado', aisle:'Congelados', unit:'bolsa', hue:200, tags:['bacalao','congelado'] },
  { id:'x-calamares-congelados', name:'Calamares congelados', aisle:'Congelados', unit:'bolsa', hue:200, tags:['calamares','congelados'] },
  { id:'x-langostinos-congelados', name:'Langostinos congelados', aisle:'Congelados', unit:'bolsa', hue:200, tags:['langostinos','congelados'] },
  { id:'x-hamburguesas-congeladas', name:'Hamburguesas congeladas', aisle:'Congelados', unit:'bolsa', hue:200, tags:['hamburguesas','congeladas'] },
  { id:'x-albondigas-congeladas', name:'Albóndigas congeladas', aisle:'Congelados', unit:'bolsa', hue:200, tags:['albondigas','congeladas'] },
  { id:'x-lasana-congelada', name:'Lasaña congelada', aisle:'Congelados', unit:'bolsa', hue:200, tags:['lasana','congelada'] },
  { id:'x-canelones-congelados', name:'Canelones congelados', aisle:'Congelados', unit:'bolsa', hue:200, tags:['canelones','congelados'] },
  { id:'x-pizza-congelada', name:'Pizza congelada', aisle:'Congelados', unit:'bolsa', hue:200, tags:['pizza','congelada'] },
  { id:'x-empanadillas-congeladas', name:'Empanadillas congeladas', aisle:'Congelados', unit:'bolsa', hue:200, tags:['empanadillas','congeladas'] },
  { id:'x-helado-de-vainilla', name:'Helado de vainilla', aisle:'Congelados', unit:'bolsa', hue:200, tags:['helado','de','vainilla'] },
  { id:'x-helado-de-chocolate', name:'Helado de chocolate', aisle:'Congelados', unit:'bolsa', hue:200, tags:['helado','de','chocolate'] },
  { id:'x-cubitos-de-hielo', name:'Cubitos de hielo', aisle:'Congelados', unit:'bolsa', hue:200, tags:['cubitos','de','hielo'] },
  { id:'x-baguette', name:'Baguette', aisle:'Panadería', unit:'ud', hue:35, tags:['baguette'] },
  { id:'x-chapata', name:'Chapata', aisle:'Panadería', unit:'ud', hue:35, tags:['chapata'] },
  { id:'x-pan-integral', name:'Pan integral', aisle:'Panadería', unit:'ud', hue:35, tags:['pan','integral'] },
  { id:'x-pan-multicereal', name:'Pan multicereal', aisle:'Panadería', unit:'ud', hue:35, tags:['pan','multicereal'] },
  { id:'x-pan-de-centeno', name:'Pan de centeno', aisle:'Panadería', unit:'ud', hue:35, tags:['pan','de','centeno'] },
  { id:'x-pan-sin-gluten', name:'Pan sin gluten', aisle:'Panadería', unit:'ud', hue:35, tags:['pan','sin','gluten'] },
  { id:'x-tortas-de-aceite', name:'Tortas de aceite', aisle:'Panadería', unit:'ud', hue:35, tags:['tortas','de','aceite'] },
  { id:'x-croissants', name:'Croissants', aisle:'Panadería', unit:'ud', hue:35, tags:['croissants'] },
  { id:'x-bollos-de-leche', name:'Bollos de leche', aisle:'Panadería', unit:'ud', hue:35, tags:['bollos','de','leche'] },
  { id:'x-picos-de-pan', name:'Picos de pan', aisle:'Panadería', unit:'ud', hue:35, tags:['picos','de','pan'] },
  { id:'x-colines', name:'Colines', aisle:'Panadería', unit:'ud', hue:35, tags:['colines'] },
  { id:'x-panecillos', name:'Panecillos', aisle:'Panadería', unit:'ud', hue:35, tags:['panecillos'] },
  { id:'x-molletes', name:'Molletes', aisle:'Panadería', unit:'ud', hue:35, tags:['molletes'] },
  { id:'x-focaccia', name:'Focaccia', aisle:'Panadería', unit:'ud', hue:35, tags:['focaccia'] },
  { id:'x-brioche', name:'Brioche', aisle:'Panadería', unit:'ud', hue:35, tags:['brioche'] },
];
